server:
  port: ${APPLICATION_PORT:8085}
---
spring:
  application:
    name: pinnaper
  datasource:
    url: jdbc:h2:file:c:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus


